Repository PedroRosa-Gif/scientifIC, pull requests merged in 2023-05, with the labels that each got.

#44 Feature/Cadastro de ICs tela de professor
  server/app/controllers/scientificResearch.controller.ts
  server/app/interfaces/IScientificResearch.ts
  server/app/models/scientificResearch.model.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/services/scientificResearch.service.ts
  server/app/services/user.service.ts
  server/app/tests/scientificResearch.test.ts
  server/app/utils/enums/ResearchStatus.ts
  server/app/utils/enums/UserType.ts
  server/index.ts
  web/src/App.tsx
  web/src/apis/scientificResearch.endpoint.ts
  web/src/assets/imgs/logo-teacher.png
  web/src/components/Authorized.tsx
  web/src/components/Authorized/Authorized.tsx
  web/src/components/BaseCheckBox.tsx
  web/src/components/BaseDataList.tsx
  web/src/components/BaseHeader.tsx
  web/src/components/BaseList.tsx
  web/src/components/BaseSelectInput.tsx
  web/src/components/BaseTextInput.tsx
  web/src/components/ButtonSign.tsx
  web/src/components/ContainerResearch.tsx
  web/src/components/EmptyList.tsx
  web/src/components/LandingStudyCard.tsx
  web/src/components/Notifier.tsx
  web/src/components/SelectAreas.tsx
  web/src/components/SelectInput.tsx
  web/src/components/SkillList.tsx
  web/src/components/TextAreaInput.tsx
  web/src/components/forms/FormScientificResearch.tsx
  web/src/components/postLoads/PostLoadScientificResearch.tsx
  web/src/interfaces/IScientificResearch.ts
  web/src/pages/LandingPage.tsx
  web/src/pages/ScientificResearch/CreateScientificResearch.tsx
  web/src/styles/BaseCheckBox.css
  web/src/styles/BaseHeader.css
  web/src/styles/BaseInput.css
  web/src/styles/ContainerResearch.css
  web/src/styles/Empty.css
  web/src/styles/FormScientificResearch.css
  web/src/styles/LandingPage.css
  web/src/styles/LandingStudyCard.css
  web/src/styles/Loading.css
  web/src/styles/Notifier.css
  web/src/styles/SelectAreas.css
  web/src/styles/SkillList.css
  web/src/styles/TextArea.css
  web/src/utils/constants/allAreas.constants.ts
  web/src/utils/constants/allStatus.constants.ts
  web/src/utils/helpers/Notificator.ts
  web/src/utils/helpers/Validate.ts
Labels: Historia, Sprint2

#45 Feature/Filtrar ICs
  docs/.gitkeep
  server/app/controllers/scientificResearch.controller.ts
  server/app/interfaces/IFiltersScientificResearch.ts
  server/app/interfaces/IScientificResearch.ts
  server/app/interfaces/IUser.ts
  server/app/models/scientificResearch.model.ts
  server/app/models/user.model.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/services/scientificResearch.service.ts
  server/app/services/user.service.ts
  server/app/tests/scientificResearch.test.ts
  server/app/tests/user.test.ts
  web/package.json
  web/src/App.tsx
  web/src/apis/scientificResearch.endpoint.ts
  web/src/assets/icons/search_icon.svg
  web/src/assets/imgs/logo-azul.png
  web/src/components/ButtonOrange.tsx
  web/src/components/DatalistInput.tsx
  web/src/components/DivPagination.tsx
  web/src/components/Footer.tsx
  web/src/components/ScientificResearchCard.tsx
  web/src/components/SelectInput.tsx
  web/src/components/TextInput.tsx
  web/src/components/forms/FormScientificResearch.tsx
  web/src/interfaces/IScientificResearch.ts
  web/src/interfaces/IUser.ts
  web/src/pages/ICsPage.tsx
  web/src/pages/LandingPage.tsx
  web/src/pages/ScientificResearch/CreateScientificResearch.tsx
  web/src/pages/SignUp.tsx
  web/src/styles/ButtonOrange.css
  web/src/styles/DatalistInput.css
  web/src/styles/DivPagination.css
  web/src/styles/ICsPage.css
  web/src/styles/LandingPage.css
  web/src/styles/ScientificResearchCard.css
  web/src/styles/TextInput.css
  web/src/utils/constants/.gitkeep
  web/src/utils/constants/allAreas.constants.ts
  web/src/utils/constants/allInstitutes.constants.ts
Labels: Sprint2

#46 Feature/Candidatar-se a uma IC
  server/app/controllers/scientificResearch.controller.ts
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/interfaces/IScientificResearchApplication.ts
  server/app/models/scientificResearchApplication.model.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/routes/scientificResearchApplication.routes.ts
  server/app/services/scientificResearch.service.ts
  server/app/services/scientificResearchApplication.service.ts
  server/app/services/user.service.ts
  server/app/tests/scientificResearch.test.ts
  server/app/tests/scientificResearchApplication.test.ts
  server/app/utils/enums/ResearchStatus.ts
  server/index.ts
  web/package-lock.json
  web/package.json
  web/src/apis/scientificResearchApplication.endpoint.ts
  web/src/components/ApplyToScientificResearchCard.tsx
  web/src/components/CardContainerBlack.tsx
  web/src/components/ScientificResearchCard.tsx
  web/src/components/postLoads/PostLoadScientificResearch.tsx
  web/src/contexts/auth.tsx
  web/src/interfaces/IScientificResearch.ts
  web/src/interfaces/IUser.ts
  web/src/pages/ICsPage.tsx
  web/src/pages/LandingPage.tsx
  web/src/pages/Login.tsx
  web/src/pages/SignUp.tsx
  web/src/styles/ApplyToAScientifResearchCard.css
  web/src/styles/ButtonOrange.css
  web/src/styles/CardContainerBlack.css
  web/src/styles/LandingPage.css
  web/src/styles/ScientificResearchCard.css
  web/src/utils/constants/allStatus.constants.ts
  web/src/utils/enums/ResearchStatus.ts
  web/src/utils/enums/UserType.ts
  web/src/utils/helpers/.gitkeep
  web/tsconfig.json
Labels: Sprint2

#48 Implementação das services dos componentes para o padrão de projeto: Singleton
  server/app/controllers/scientificResearch.controller.ts
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/controllers/user.controller.ts
  server/app/interfaces/IUser.ts
  server/app/models/user.model.ts
  server/app/services/ScientificResearchApplicationService.ts
  server/app/services/UserService.ts
  server/app/services/scientificResearch.service.ts
  server/app/services/scientificResearchApplication.service.ts
  server/app/services/user.service.ts
  server/app/tests/scientificResearch.test.ts
  server/app/tests/scientificResearchApplication.test.ts
  server/app/tests/user.test.ts
Labels: Avaliação A4.1

#50 Feature/CandidaturasICsTelaProfessor
  server/app/controllers/scientificResearch.controller.ts
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/routes/scientificResearchApplication.routes.ts
  server/app/services/ScientificResearchApplicationService.ts
  server/app/services/ScientificResearchService.ts
  server/app/tests/scientificResearch.test.ts
  web/src/App.tsx
  web/src/apis/scientificResearch.endpoint.ts
  web/src/apis/scientificResearchApplication.endpoint.ts
  web/src/components/ApplicationResearchCard.tsx
  web/src/components/Footer.tsx
  web/src/interfaces/IScientificResearchApplication.ts
  web/src/pages/ScientificResearch/CreateScientificResearch.tsx
  web/src/pages/ScientificResearch/ScientificResearchApplications.tsx
  web/src/styles/ApplicationResearchCard.css
  web/src/styles/ScientifyResearchApplications.css
Labels: Historia, Sprint2

#49 Feature/Aluno filtra ICs de interesse
  server/app/services/ScientificResearchService.ts
  web/src/components/ScientificResearchCard.tsx
  web/src/interfaces/IUser.ts
  web/src/pages/ICsPage.tsx
  web/src/pages/SignUp.tsx
Labels: Sprint2

#51 Feature/listar candidaturas
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/controllers/user.controller.ts
  server/app/routes/scientificResearchApplication.routes.ts
  server/app/routes/user.routes.ts
  server/app/services/ScientificResearchApplicationService.ts
  server/app/services/UserService.ts
  web/public/favicon.ico
  web/src/App.tsx
  web/src/apis/scientificResearchApplication.endpoint.ts
  web/src/apis/user.endpoint.ts
  web/src/assets/icons/add_icon.svg
  web/src/assets/icons/cancel_icon.svg
  web/src/assets/icons/cancel_icon_white.svg
  web/src/assets/icons/edit_icon.svg
  web/src/assets/icons/expand_icon.svg
  web/src/assets/icons/ic_icon.svg
  web/src/assets/icons/logout_icon.svg
  web/src/assets/icons/profile_icon.svg
  web/src/assets/icons/unicamp_icon.svg
  web/src/assets/imgs/blue_planet.png
  web/src/assets/imgs/earth_planet.png
  web/src/assets/imgs/green_planet.png
  web/src/assets/imgs/photo_profile.svg
  web/src/assets/imgs/pink_planet.png
  web/src/assets/imgs/saturn_planet.png
  web/src/components/ButtonProfile.tsx
  web/src/components/CardContainerBlack.tsx
  web/src/components/IconProfile.tsx
  web/src/components/Logo.tsx
  web/src/components/Topic.tsx
  web/src/components/TopicsProfile/EditProfile.tsx
  web/src/components/TopicsProfile/ListAreas.tsx
  web/src/components/TopicsProfile/ListCandidacy.tsx
  web/src/components/VerifyPopup.tsx
  web/src/interfaces/IUser.ts
  web/src/pages/Login.tsx
  web/src/pages/Profile.tsx
  web/src/pages/SignUp.tsx
  web/src/styles/ButtonProfile.css
  web/src/styles/EditProfile.css
  web/src/styles/IconProfile.css
  web/src/styles/ListAreas.css
  web/src/styles/ListCandidacy.css
  web/src/styles/Logo.css
  web/src/styles/Notifier.css
  web/src/styles/Profile.css
  web/src/styles/Topic.css
  web/src/styles/VerifyPopup.css
  web/src/utils/constants/allAreas.contants.ts
  web/src/utils/constants/fieldsProfile.constants.ts
  web/src/utils/handleFormatString.ts
Labels: Sprint2

#52 Feature/Aprovar Aluno IC pelo professor
  server/app/controllers/scientificResearch.controller.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/services/ScientificResearchService.ts
  server/app/tests/scientificResearch.test.ts
  web/src/apis/scientificResearch.endpoint.ts
  web/src/components/ApplicationApprove.tsx
  web/src/components/ApplicationResearchCard.tsx
  web/src/components/BaseHeader.tsx
  web/src/pages/ICsPage.tsx
  web/src/pages/LandingPage.tsx
  web/src/pages/ScientificResearch/ScientificResearchApplications.tsx
  web/src/styles/ApplicationApprove.css
  web/src/styles/BaseHeader.css
Labels: Sprint2
