Repository PedroRosa-Gif/scientifIC, pull requests merged in 2023-06, with the labels that each got.

#56 Hotfix/refatoracao a4.2
  server/app/controllers/scientificResearch.controller.ts
  server/app/services/ScientificResearchService.ts
  server/app/utils/helpers/applyPagination.ts
  web/src/components/AuthorizedMenu.tsx
  web/src/components/ICsCardArea.tsx
  web/src/pages/ICsPage.tsx
  web/src/pages/LandingPage.tsx
  web/src/pages/ScientificResearch/CreateScientificResearch.tsx
Labels: Avaliação A4.2

#57 Adicionando a funcionalidade de listagem de ics na tela de perfil
  server/app/controllers/scientificResearch.controller.ts
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/services/ScientificResearchApplicationService.ts
  server/app/services/ScientificResearchService.ts
  web/src/apis/scientificResearch.endpoint.ts
  web/src/apis/scientificResearchApplication.endpoint.ts
  web/src/components/TopicsProfile/ListCandidacy.tsx
  web/src/components/TopicsProfile/ListMyICs.tsx
  web/src/pages/Profile.tsx
  web/src/styles/ListCandidacy.css
  web/src/styles/Profile.css
Labels: Historia

#59 Feature/Modificação de IC
  server/app/controllers/scientificResearch.controller.ts
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/controllers/scientificResearchEvent.controller.ts
  server/app/interfaces/IScientificResearchEvent.ts
  server/app/middleware/authentication.ts
  server/app/models/scientificResearchEvent.model.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/routes/scientificResearchEvent.routes.ts
  server/app/services/ScientificResearchEventService.ts
  server/app/services/ScientificResearchService.ts
  server/index.ts
  web/src/App.tsx
  web/src/apis/scientificResearch.endpoint.ts
  web/src/apis/scientificResearchEvent.endpoint.ts
  web/src/components/CardNewEvent.tsx
  web/src/components/EventsResearch.tsx
  web/src/components/UserBox.tsx
  web/src/components/forms/FormOnGoingResearch.tsx
  web/src/interfaces/IScientificResearchEvent.ts
  web/src/pages/ScientificResearch/OnGoingScientificResearch.tsx
  web/src/styles/CardNewEvent.css
  web/src/styles/EventsResearch.css
  web/src/styles/OnGoingScientificResearch.css
  web/src/styles/UserBox.css
Labels: Historia

#61 Feature/listar i cs criadas
  server/app/controllers/scientificResearch.controller.ts
  server/app/services/ScientificResearchService.ts
  web/src/apis/scientificResearch.endpoint.ts
  web/src/components/TopicsProfile/ListMyICs.tsx
  web/src/pages/Profile.tsx
  web/src/styles/Profile.css
  web/src/utils/constants/topicsProfile.constants.ts
Labels: Historia

#62 Hotfix/perfil
  web/src/components/TopicsProfile/EditProfile.tsx
  web/src/components/VerifyPopup.tsx
  web/src/styles/VerifyPopup.css
Labels: bug

#64 Feature/cancelamento exclusao ic
  server/app/controllers/scientificResearch.controller.ts
  server/app/controllers/scientificResearchEvent.controller.ts
  server/app/interfaces/IScientificResearch.ts
  server/app/middleware/authentication.ts
  server/app/models/scientificResearch.model.ts
  server/app/routes/scientificResearch.routes.ts
  server/app/routes/scientificResearchEvent.routes.ts
  server/app/services/ScientificResearchService.ts
  server/app/services/UserService.ts
  server/app/tests/scientificResearch.test.ts
  server/app/tests/scientificResearchApplication.test.ts
  web/src/App.tsx
  web/src/apis/scientificResearch.endpoint.ts
  web/src/apis/scientificResearchEvent.endpoint.ts
  web/src/assets/icons/block_icon.svg
  web/src/assets/icons/open_icon.svg
  web/src/components/ApplicationApprove.tsx
  web/src/components/CancelICButton.tsx
  web/src/components/ErrorBox.tsx
  web/src/components/TopicsProfile/ListAreas.tsx
  web/src/components/TopicsProfile/ListCandidacy.tsx
  web/src/components/TopicsProfile/ListMyICs.tsx
  web/src/components/UserBox.tsx
  web/src/components/forms/FormOnGoingResearch.tsx
  web/src/components/forms/FormScientificResearch.tsx
  web/src/interfaces/IScientificResearch.ts
  web/src/pages/ScientificResearch/CreateScientificResearch.tsx
  web/src/pages/ScientificResearch/EditScientificResearch.tsx
  web/src/pages/ScientificResearch/OnGoingScientificResearch.tsx
  web/src/pages/ScientificResearch/ScientificResearchApplications.tsx
  web/src/styles/ApplicationResearchCard.css
  web/src/styles/CancelICButton.css
  web/src/styles/ErrorBox.css
  web/src/styles/ICsPage.css
  web/src/styles/ListCandidacy.css
  web/src/styles/OnGoingScientificResearch.css
  web/src/styles/ScientifyResearchApplications.css
Labels: Historia

#66 Testes para avaliação A5
  .github/workflows/ci.react.yml
  package-lock.json
  server/app/controllers/scientificResearchApplication.controller.ts
  server/app/interfaces/IScientificResearchEvent.ts
  server/app/services/ScientificResearchApplicationService.ts
  server/app/tests/scientificResearchApplication.test.ts
  server/app/tests/scientificResearchEvent.test.ts
  web/jest.config.ts
  web/package-lock.json
  web/package.json
  web/src/pages/SignUp.tsx
  web/src/tests/signup.test.ts
  web/src/utils/helpers/validadeSignupFields.ts
Labels: Avaliação A5
